name: MEVN Stack CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code of client
      uses: actions/checkout@v3

    - name: Setup Node.js for client
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install client dependencies
      working-directory: ./client
      run: npm install

    - name: Install server dependencies
      working-directory: ./server
      run: npm install

    - name: Build Vue.js Client
      run: npm run build --prefix client

    - name: Clean up server/public
      run: rm -rf server/public/*

    - name: Move Built Client Assets to Server Public
      run: cp -r client/dist/* server/public/

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add server/public/
        git commit -m "Updated server/public with latest build"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
